
module Blockchain.VM.OpcodePrices where

import Prelude hiding (EQ, LT, GT)

import Blockchain.VM.Opcodes

opGasPrice::Operation->Integer
opGasPrice DUP1 =	3
opGasPrice DUP2 =	3
opGasPrice DUP3 =	3
opGasPrice DUP4 =	3
opGasPrice DUP5 =	3
opGasPrice DUP6 =	3
opGasPrice DUP7 =	3
opGasPrice DUP8 =	3
opGasPrice DUP9 =	3
opGasPrice DUP10 =	3
opGasPrice DUP11 =	3
opGasPrice DUP12 =	3
opGasPrice DUP13 =	3
opGasPrice DUP14 =	3
opGasPrice DUP15 =	3
opGasPrice DUP16 =	3
opGasPrice SWAP1 =	3
opGasPrice SWAP2 =	3
opGasPrice SWAP3 =	3
opGasPrice SWAP4 =	3
opGasPrice SWAP5 =	3
opGasPrice SWAP6 =	3
opGasPrice SWAP7 =	3
opGasPrice SWAP8 =	3
opGasPrice SWAP9 =	3
opGasPrice SWAP10 =	3
opGasPrice SWAP11 =	3
opGasPrice SWAP12 =	3
opGasPrice SWAP13 =	3
opGasPrice SWAP14 =	3
opGasPrice SWAP15 =	3
opGasPrice SWAP16 =	3
opGasPrice (PUSH _) =	3
opGasPrice ADD =	3
opGasPrice MUL =	5
opGasPrice SUB =	3
opGasPrice DIV =	5
opGasPrice SDIV =	5
opGasPrice MOD =	5
opGasPrice SMOD =	5
opGasPrice ADDMOD =	8
opGasPrice MULMOD =	8
--opGasPrice EXPBASE =	10
--opGasPrice EXPBYTE =	10
opGasPrice SIGNEXTEND =	5
opGasPrice LT =	3
opGasPrice GT =	3
opGasPrice SLT =	3
opGasPrice SGT =	3
opGasPrice EQ =	3
opGasPrice ISZERO =	3
opGasPrice AND =	3
opGasPrice OR =	3
opGasPrice XOR =	3
opGasPrice NOT =	3
opGasPrice BYTE =	3
--opGasPrice SHA3BASE =	30
--opGasPrice SHA3WORD =	6
--opGasPrice ECRECOVER =	3000
--opGasPrice SHA256BASE =	60
--opGasPrice SHA256WORD =	12
--opGasPrice RIPEMD160BASE =	600
--opGasPrice RIPEMD160WORD =	120
--opGasPrice IDENTITYBASE =	15
--opGasPrice IDENTITYWORD =	3
opGasPrice ADDRESS =	2
opGasPrice BALANCE =	20
opGasPrice ORIGIN =	2
opGasPrice CALLER =	2
opGasPrice CALLVALUE =	2
opGasPrice CALLDATALOAD =	3
opGasPrice CALLDATASIZE =	2
--opGasPrice CALLDATACOPYBASE =	3
opGasPrice CODESIZE =	2
--opGasPrice CODECOPYBASE =	3
opGasPrice GASPRICE =	2
opGasPrice EXTCODESIZE =	20
--opGasPrice EXTCODECOPYBASE =	20
--opGasPrice GCOPYWORD =	3
opGasPrice BLOCKHASH =	20
opGasPrice COINBASE =	2
opGasPrice TIMESTAMP =	2
opGasPrice NUMBER =	2
opGasPrice DIFFICULTY =	2
opGasPrice GASLIMIT =	2
opGasPrice POP =	2
opGasPrice MLOAD =	3
opGasPrice MSTORE =	3
opGasPrice MSTORE8 =	3
opGasPrice SLOAD =	50
--opGasPrice STORAGEADD =	200
--opGasPrice STORAGEMOD =	200
--opGasPrice STORAGEKILL =	200
opGasPrice JUMP =	8
opGasPrice JUMPI =	10
opGasPrice PC =	2
opGasPrice MSIZE =	2
opGasPrice GAS =	2
opGasPrice JUMPDEST =	1
--opGasPrice GLOG =	32
--opGasPrice GLOGTOPIC =	20
--opGasPrice GLOGDATA =	1
opGasPrice CREATE =	40
--opGasPrice CREATEDATA =	3
opGasPrice CALL =	40
opGasPrice CALLCODE =	40
--opGasPrice GCALLVALUETRANSFER =	
--opGasPrice GCALLSTIPEND =	
--opGasPrice GCALLNEWACCOUNT =	
opGasPrice RETURN =	0
opGasPrice STOP =	0
opGasPrice SUICIDE =	0
--opGasPrice GSUICIDEREFUND =	
--opGasPrice MEMWORD =	3
--opGasPrice QUADCOEFFDIV =	
--opGasPrice GTX =	10000
--opGasPrice GTXDATANONZERO =	
--opGasPrice GTXDATAZERO =

opGasPrice (MalformedOpcode _) = 0 --gonna fail anyway, just put something arbitrary here

opGasPrice x = error $ "Missing opcode in opCodePrice: " ++ show x
